import gatsby from "./gatsby.svg";
import github from "./github.svg";
import appDevelopment from "./app-development.svg";
import apollo from "./apollo.svg";
import cloudfront from "./aws-cloudfront.svg";
import dynamoDb from "./aws-dynamodb.svg";
import ec2 from "./aws-ec2.svg";
import lambda from "./aws-lambda2.svg";
import aws from "./aws.svg";
import css from "./css.svg";
import d3 from "./d3.svg";
import expo from "./expo.svg";
import firebase from "./firebase-1.svg";
import flutter from "./flutter.svg";
import go from "./go.svg";
import graphql from "./graphql.svg";
import html from "./html.svg";
import javascript from "./javascript.svg";
import json from "./json.svg";
import mui from "./mui.svg";
import nextjs from "./next-js.svg";
import pyhon from "./python.svg";
import reactNative from "./react-native.svg";
import react from "./react.svg";
import redux from "./redux.svg";
import tailwind from "./tailwind-css.svg";
import vite from "./vitejs.svg";
import vscode from "./vscode.svg";
import adobeIllustrator from "./adobe-illustrator.svg";
import adobeXd from "./adobe-xd.svg";
import bitbucket from "./bitbucket.svg";
import git from "./git.svg";
import github2 from "./github2.svg";
import gitlab from "./gitlab.svg";
import mongodb from "./mongodb.svg";
import mysql from "./mysql.svg";
import nodejs from "./nodejs.svg";
import winodows from "./windows.svg";

export const gatsbyLogo = gatsby;
export const githubLogo = github;
export const appDevelopmentSvg = appDevelopment;
export const apolloLogo = apollo;
export const cloudfrontLogo = cloudfront;
export const dynamoDbLogo = dynamoDb;
export const ec2Logo = ec2;
export const lambdaLogo = lambda;
export const awsLogo = aws;
export const cssLogo = css;
export const d3Logo = d3;
export const expoLogo = expo;
export const firebaseLogo = firebase;
export const flutterLogo = flutter;
export const goLogo = go;
export const graphqlLogo = graphql;
export const htmlLogo = html;
export const javascriptLogo = javascript;
export const jsonLogo = json;
export const muiLogo = mui;
export const nextjsLogo = nextjs;
export const pyhonLogo = pyhon;
export const reactNativeLogo = reactNative;
export const reactLogo = react;
export const reduxLogo = redux;
export const tailwindLogo = tailwind;
export const viteLogo = vite;
export const vscodeLogo = vscode;
export const adobeIllustratorLogo = adobeIllustrator;
export const adobeXdLogo = adobeXd;
export const bitbucketLogo = bitbucket;
export const gitLogo = git;
export const github2Logo = github2;
export const gitlabLogo = gitlab;
export const mongodbLogo = mongodb;
export const mysqlLogo = mysql;
export const nodejsLogo = nodejs;
export const winodowsLogo = winodows;
